name: one_better_a_day
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # DI
  get_it: ^8.0.2

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2

  # Bloc
  flutter_bloc: ^8.1.6
  bloc_event_transformers: ^1.0.2+1
  bloc_concurrency: 0.2.5


  # Storage
  shared_preferences: ^2.3.3
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  flutter_dotenv: ^5.2.1

  # Comparison
  equatable: ^2.0.7
  collection: ^1.18.0

  # Logger
  logger: ^2.5.0

  # AI
  internet_connection_checker: ^3.0.1
  google_generative_ai: ^0.4.6

  # Utils
  uuid: ^4.5.1
  json_annotation: ^4.9.0

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Image
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_svg_provider: ^1.0.7
  hl_image_picker: ^1.2.16
  path_provider: ^2.1.5
  path: ^1.9.0
  image_gallery_saver_plus: ^3.0.5

  # UI
  flutter_slider_drawer: ^2.1.3
  flutter_settings_ui: ^3.0.1
  flutter_login: ^5.0.0
  flutter_advanced_avatar: ^1.5.2
  awesome_snackbar_content: ^0.1.4
  numberpicker: ^2.1.2
  flutter_smart_dialog: ^4.9.8+5
  awesome_dialog: ^3.2.1
  syncfusion_flutter_datepicker: ^28.1.39
  percent_indicator: ^4.2.4
  dropdown_button2: ^2.3.9
  syncfusion_flutter_sliders: ^28.1.39
  msh_checkbox: ^2.0.1
  animated_text_kit: ^4.2.2
  rounded_loading_button_plus: ^3.0.1
  liquid_progress_indicator_v2: ^0.5.0
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  table_calendar: ^3.1.2
  bottom_picker: ^2.9.0
  custom_pop_up_menu: ^1.2.4
  fl_chart: ^0.70.1
  buttons_tabbar: ^1.3.14
  toggle_switch: ^2.3.0
  fl_heatmap: ^0.4.5
  flutter_swipe_action_cell: ^3.1.5
  animated_react_button: ^0.0.4
  google_nav_bar: ^5.0.7
  flutter_carousel_widget: ^3.1.0
  super_tooltip: ^2.0.9
  loading_indicator: ^3.1.1
  material_tag_editor: ^0.1.2
  elegant_notification: ^2.4.1

  # Form
  formz: ^0.8.0

  # Icon
  font_awesome_flutter: ^10.8.0
  animated_emoji: ^3.1.0
  iconify_flutter_plus: ^1.0.4
  colorful_iconify_flutter: ^0.0.5

  # DateTime
  moment_dart: ^3.1.0

  # Animation
  page_transition: ^2.1.0
  flutter_bounce: ^1.1.0
  flutter_slidable: ^3.1.1
  animated_switcher_plus: ^1.1.0
  flutter_animate: ^4.5.2

  # Permission
  permission_handler: ^11.3.1

  # Map & Geo
  geolocator: 13.0.2

  # Service
  flutter_foreground_task: ^8.17.0
  awesome_notifications_core: ^0.10.0
  awesome_notifications: ^0.10.0

  # Share
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  hive_ce_generator: ^1.8.1
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/animations/
    - assets/animations/mood/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
